### ISSUE TITLE
d3d11.dll causes half of screen to load

### ISSUE THREAD

**Issue by RoryAnderson077** [PolarWizard/HackGULastRecodeFix#1]
i follow the instructions, running 3440x1440, only half the screen shows

![Image](https://github.com/user-attachments/assets/4f208dc3-3c48-4f7d-9012-b0b6793a84c3)

![Image](https://github.com/user-attachments/assets/6b92f428-e614-4f84-ac6d-fa75a1704d3f)

**Comment by PolarWizard** [comment]
d3d11.dll is not the root cause of the issue, if anything it shows the mod is doing something albeit incorrectly given the messed up screen lol. Unfortunately I cannot recreate this on a 21:9 display.

To fix try doing:
1. Verify integrity of game files: `right click game in steam library -> Properties... -> Installed Files -> Verify integrity of game files`
2. Navigate to `Hack GU/scripts` and delete the `patch.txt` file
3. Make sure resolution setting in `HackGULastRecodeFix.yml` is correct 
4. Rerun `HackGULastRecodePatch.exe` 
5. Play game
6. If all is good the very first thing you should see on game boot up is:

![Image](https://github.com/user-attachments/assets/3a9ef9e6-599d-45e2-a1ee-2e7768f20a6c)

**Comment by PolarWizard** [comment]
Closing due to inactivity, assuming the issue is resolved on user end

**Comment by krakerz** [comment]
hello, first thanks for making this mod, since i just wanna start playing this game now, here the more information for this issue (it still happens and i think i know what's the issue is)
step to reproduce : 
1. install the mod as instructed
2. run the game
3. go to option (in main menu)
4. go to steam option
5. go to graphic options
6. change the antialiasing to high
https://github.com/user-attachments/assets/32456fd0-3776-476f-b943-b5ea8459812b

**Comment by PolarWizard** [comment]
Thank you @krakerz for the info and work around for this issue, this has been fixed in v1.0.1.
